In [1]:
import numpy as np


np.random.seed(42)  # For reproducibility

# Generate two independent column vectors 
col1 = np.random.randn(5, 1)
col2 = np.random.randn(5, 1)

# Generate two dependent columns 
col3 = 2 * col1 + 3 * col2
col4 = -1 * col1 + 4 * col2

# Construct matrix A with rank 2
A = np.hstack([col1, col2, col3, col4])

# Step 2: Create a 5×1 vector b that lies in the column space of A
x_particular = np.array([[1], [2], [0], [0]])  # Choosing arbitrary particular solution
b = A @ x_particular  # Ensure b is in Col(A)

# Step 3: Solve Ax = b using least squares to find a particular solution
x_pseudo = np.linalg.pinv(A) @ b  # A pseudo-inverse solution

# Step 4: Find infinite solutions by adding the null space solutions
U, S, Vt = np.linalg.svd(A)  # Compute SVD
null_space = Vt.T[:, 2:]  # Basis of the null space (since rank = 2, last 2 columns are null space)

# Generate infinite solutions by varying the null space components
print("Infinite Solutions:")
for i in range(5):  # Generate 5 different solutions
    alpha = np.random.randn(2, 1)  # Random coefficients for null space vectors
    x_solution = x_pseudo + null_space @ alpha
    print(f"Solution {i+1}:\n", x_solution, "\n")


Infinite Solutions:
Solution 1:
 [[0.66029913]
 [0.40047277]
 [0.26893915]
 [0.19817744]] 

Solution 2:
 [[ 0.37280458]
 [ 1.94326715]
 [ 0.23322859]
 [-0.16073823]] 

Solution 3:
 [[ 1.79367003]
 [ 0.19690832]
 [-0.12468986]
 [ 0.54429031]] 

Solution 4:
 [[ 0.96435713]
 [-0.47048443]
 [ 0.23755054]
 [ 0.43945821]] 

Solution 5:
 [[ 1.2701707 ]
 [ 1.19716594]
 [-0.02525898]
 [ 0.21965275]] 

