In [1]:
import numpy as np

# Define matrix A
A = np.array([
    [1, 2, 3, 4],
    [2, 3, 4, 5],
    [5, 8, 11, 14],
    [3, 5, 7, 9]
])

# Compute rank of A
rank_A = np.linalg.matrix_rank(A)
print(f"Rank of A: {rank_A}")

# Generate 10 random b vectors ensuring no solution
no_solution_b_vectors = []

while len(no_solution_b_vectors) < 10:
    b = np.random.randint(-10, 10, (4, 1))  # Generate random 4x1 vector b
    augmented_matrix = np.hstack([A, b])  # Augmented matrix [A|b]
    rank_augmented = np.linalg.matrix_rank(augmented_matrix)

    if rank_augmented > rank_A:
        no_solution_b_vectors.append(b)

# Print the 10 b vectors that have no solution
print("\n10 b vectors for which Ax = b has no solution:\n")
for i, b in enumerate(no_solution_b_vectors):
    print(f"b_{i+1}:\n{b.flatten()}\n")


Rank of A: 2

10 b vectors for which Ax = b has no solution:

b_1:
[ 1 -4  8 -1]

b_2:
[  0 -10  -2  -6]

b_3:
[ 6  4  0 -9]

b_4:
[ 8 -9  7 -5]

b_5:
[-5  4 -6 -7]

b_6:
[-1  5 -2  4]

b_7:
[ 8  5 -1  6]

b_8:
[-9  6  9 -6]

b_9:
[-6 -6  0  3]

b_10:
[-1  7 -5 -8]

